services:

    endroid_user.user_manager:
        class: Endroid\Bundle\UserBundle\Model\UserManager
        public: false
        parent: fos_user.user_manager.default
        calls:
            - [ setContainer, [@service_container] ]
