parameters:
    endroid_user.user.handler.class: Endroid\Bundle\UserBundle\Handler\UserHandler
    endroid_user.user.class: Endroid\Bundle\UserBundle\Entity\User

services:
    endroid_user.user_manager:
        class: Endroid\Bundle\UserBundle\Model\UserManager
        public: false
        parent: fos_user.user_manager.default
        calls:
            - [ setContainer, [@service_container] ]

    endroid_user.user.handler:
        class: %endroid_user.user.handler.class%
        arguments: [ @doctrine.orm.entity_manager, %endroid_user.user.class% ]
