tools:
    external_code_coverage:
        enabled:              false

    php_code_coverage:
        enabled:              false

    php_code_sniffer:
        enabled:              true
        command:              phpcs
        config:
            standard:         PSR2
        filter:
            excluded_paths:
                - 'bin/*'
                - 'vendor/*'
                - 'features/*'

    php_cpd:
        enabled:              true
        command:              phpcpd
        excluded_dirs:
            - 'bin/*'
            - 'vendor/*'
            - 'features/*'

    php_cs_fixer:
        enabled:              true
        command:              php-cs-fixer
        config:
            level:            psr2
        filter:
            excluded_paths:
                - 'bin/*'
                - 'vendor/*'
                - 'features/*'

    php_loc:
        enabled:              true
        command:              phploc
        excluded_dirs:
            - bin
            - vendor
            - features

    php_mess_detector:
        enabled:              true
        command:              phpmd
        filter:
            excluded_paths:
                - 'bin/*'
                - 'vendor/*'
                - 'features/*'

    php_pdepend:
        enabled:              true
        command:              pdepend
        excluded_dirs:
            - bin
            - vendor
            - features

    php_analyzer:
        enabled:              true
        filter:
            excluded_paths:
                - 'bin/*'
                - 'vendor/*'
                - 'features/*'

    sensiolabs_security_checker: true