fos_elastica:
    clients:
        default: { host: localhost, port: 9200 }
    indexes:
        %search_index%:
            client: default
            finder: ~
            types:
                page:
                    mappings:
                        title: { boost: 3 }
                        content: { boost: 2 }
                        locale: ~
                        published: ~
                        slug: ~
                    persistence:
                        driver: orm
                        model: PageBundle\Entity\Page
                        provider: ~
                        finder: ~
                        listener: ~
                newsarticle:
                    mappings:
                        title: { boost: 3 }
                        content: { boost: 2 }
                        locale: ~
                        published: ~
                        slug: ~
                    persistence:
                        driver: orm
                        model: NewsBundle\Entity\Article
                        provider: ~
                        finder: ~
                        listener: ~
