endroid_rest_news_article:
    resource:     "Endroid\\Bundle\\RestBundle\\Controller\\NewsArticleController"
    type:         rest
    name_prefix:  api_

endroid_rest_page:
    resource:     "Endroid\\Bundle\\RestBundle\\Controller\\PageController"
    type:         rest
    name_prefix:  api_

endroid_rest_user:
    resource:     "Endroid\\Bundle\\RestBundle\\Controller\\UserController"
    type:         rest
    name_prefix:  api_
