services:

    endroid_menu.admin.menu:
        class: Endroid\Bundle\MenuBundle\Admin\MenuAdmin
        arguments: [null,  Endroid\Bundle\MenuBundle\Entity\MenuItem, EndroidAdminBundle:BaseAdmin]
        calls:
            - [ setContainer, [ @service_container ] ]
        tags:
            - { name: sonata.admin, manager_type: orm, group: Navigatie, label: Menus }

    endroid_menu.twig.extension:
        class: Endroid\Bundle\MenuBundle\Twig\Extension\MenuExtension
        calls:
            - [ setContainer, [ @service_container ] ]
        tags:
            - { name: twig.extension }

    endroid_menu.builder:
        class: Endroid\Bundle\MenuBundle\Menu\Builder
        arguments: ["@knp_menu.factory"]
        calls:
            - [ setContainer, [ @service_container ] ]

    endroid_menu.main:
        class: Knp\Menu\MenuItem
        factory_service: endroid_menu.builder
        factory_method: createMenuMain
        arguments: ["@request"]
        scope: request
        tags:
            - { name: knp_menu.menu, alias: menu_main }

    endroid_menu.footer:
        class: Knp\Menu\MenuItem
        factory_service: endroid_menu.builder
        factory_method: createMenuFooter
        arguments: ["@request"]
        scope: request
        tags:
            - { name: knp_menu.menu, alias: menu_footer }
