parameters:
    endroid_page.page.handler.class: Endroid\Bundle\PageBundle\Handler\PageHandler
    endroid_page.page.class: Endroid\Bundle\PageBundle\Entity\Page

services:
    endroid_page.admin.page:
        class: Endroid\Bundle\PageBundle\Admin\PageAdmin
        arguments: [ null, Endroid\Bundle\PageBundle\Entity\Page, null]
        calls:
            - [ setContainer, [ @service_container ] ]
        tags:
            - { name: sonata.admin, manager_type: orm, group: Content, label: Pages }

    endroid_page.route_provider:
        class: Endroid\Bundle\PageBundle\Service\RouteProvider
        calls:
            - [ setContainer, [ @service_container ] ]
        tags:
            -  { name: endroid_route.provider }

    endroid_page.page.handler:
        class: %endroid_page.page.handler.class%
        arguments: [ @doctrine.orm.entity_manager, %endroid_page.page.class% ]
