parameters:
    endroid_news.article.handler.class: Endroid\Bundle\NewsBundle\Handler\ArticleHandler
    endroid_news.article.class: Endroid\Bundle\NewsBundle\Entity\Article

services:
    endroid_news.admin.article:
        class: Endroid\Bundle\NewsBundle\Admin\ArticleAdmin
        arguments: [null,  Endroid\Bundle\NewsBundle\Entity\Article, null]
        calls:
            - [ setContainer, [ @service_container ] ]
        tags:
            - { name: sonata.admin, manager_type: orm, group: Content, label: News }

    endroid_news.route_provider:
        class: Endroid\Bundle\NewsBundle\Service\RouteProvider
        calls:
            - [ setContainer, [ @service_container ] ]
        tags:
            -  { name: endroid_route.provider }

    endroid_news.article.handler:
        class: %endroid_news.article.handler.class%
        arguments: [ @doctrine.orm.entity_manager, %endroid_news.article.class% ]
